#!/bin/bash
/home/joberant/NLP_2324/jonathany/anaconda3/envs/py10/bin/python -V
/home/joberant/NLP_2324/jonathany/anaconda3/envs/py10/bin/python /home/joberant/NLP_2324/jonathany/interpretability/patchscopes/code/multihop2.py  "$@"
echo Finished
